### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Ksengine** [wearerequired/lint-action#106]
I have this log. I dont know why

```
Error: Error trying to create GitHub check for stylelint: Received status code 403
    at createCheck (/home/runner/work/_actions/wearerequired/lint-action/v1/src/github/api.js:64:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
/home/runner/work/_actions/wearerequired/lint-action/v1/src/index.js:13
	throw new Error(`Exiting because of unhandled promise rejection`);
	^

Error: Exiting because of unhandled promise rejection
    at process.<anonymous> (/home/runner/work/_actions/wearerequired/lint-action/v1/src/index.js:13:8)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by ocean90** [comment]
Hi, thanks for the report. Can you￼￼ please share a link to the repo where this error has happened?

**Comment by Ksengine** [comment]
this is my repo https://github.com/KsTGTeam/Beautify

**Comment by Ksengine** [comment]
and this log
```
Error: Error trying to create GitHub check for stylelint: Received status code 403
    at createCheck (/home/runner/work/_actions/wearerequired/lint-action/v1/src/github/api.js:64:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
/home/runner/work/_actions/wearerequired/lint-action/v1/src/index.js:13
	throw new Error(`Exiting because of unhandled promise rejection`);
	^

Error: Exiting because of unhandled promise rejection
    at process.<anonymous> (/home/runner/work/_actions/wearerequired/lint-action/v1/src/index.js:13:8)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by ocean90** [comment]
It looks like you're using a custom GitHub token which doesn't have the necessary permissions. Can you try using the default token `${{ secrets.github_token }}`?

**Comment by Ksengine** [comment]
i will try

**Comment by salmonsd** [comment]
Hey @Ksengine, did you get this resolved? Looks like you still might be using a custom GitHub token, curious what you changed to correct the permissions error?
